In [ ]:
sentence = "I love Artificial Intelligence"

print("Sentence:", sentence)
print("Data Type:", type(sentence))

Sentence: I love Artificial Intelligence
Data Type: <class 'str'>

In [ ]:
sentence = "i love machine learning"

count = len(sentence)
print("count:",count)

count: 23

In [ ]:
sentence = "i love machine learning"
words = sentence.split()

count = len(words)
print("count of word:",count,words)

count of word: 4 ['i', 'love', 'machine', 'learning']

In [ ]:
message = "You have won a free prize"
if "free" in message:
  print("message contain free word")
else:
  print("message not contain free word")

message contain free word

In [ ]:
message = "Congratulations! You have won a lottery."

if "Congratulations" in message:
    print("Possible Spam")
else:
    print("Not Spam")

Possible Spam

In [ ]:
import pandas as pd

data = {
    "Review": [
        "Excellent product",
        "Very bad service",
        "Amazing quality",
        "Not worth the money"
    ],
    "Sentiment": [
        "Positive",
        "Negative",
        "Positive",
        "Negative"
    ]
}

df = pd.DataFrame(data)

print(df)

                Review Sentiment
0    Excellent product  Positive
1     Very bad service  Negative
2      Amazing quality  Positive
3  Not worth the money  Negative

In [ ]:
df.shape

(4, 2)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Review     4 non-null      object
 1   Sentiment  4 non-null      object
dtypes: object(2)
memory usage: 196.0+ bytes

In [ ]:
df.head(5)

                Review Sentiment
0    Excellent product  Positive
1     Very bad service  Negative
2      Amazing quality  Positive
3  Not worth the money  Negative

In [ ]:
df["Sentiment"].value_counts()

Sentiment
Positive    2
Negative    2
Name: count, dtype: int64

In [ ]:
df["Review"]= df["Review"].str.lower()
print(df["Review"])

0      excellent product
1       very bad service
2        amazing quality
3    not worth the money
Name: Review, dtype: object

In [ ]:
df["Review_count"] = df["Review"].apply(len)
print(df)

                Review Sentiment  Review_count  Contains_Phone
0    excellent product  Positive            17           False
1     very bad service  Negative            16           False
2      amazing quality  Positive            15           False
3  not worth the money  Negative            19           False

In [ ]:
for review in df["Review"]:
 print(review)

In [ ]:
# df["phone_contains"] = df["review"].str.contains("Phone", case = False)
# print(df)

df["Contains_Phone"] = df["Review"].str.contains("phone", case=False)

print(df)

                Review Sentiment  Review_count  Contains_Phone
0    excellent product  Positive            17           False
1     very bad service  Negative            16           False
2      amazing quality  Positive            15           False
3  not worth the money  Negative            19           False

In [ ]:
positive_reviews = df[df["Sentiment"]=="positive"]
print(positive_reviews.head())

negative_reviews = df[df["Sentiment"]=="negative"]
print(negative_reviews.head())

neutral_reviews = df[df["Sentiment"]=="neutral"]
print(neutral_reviews.head())

Empty DataFrame
Columns: [Review, Sentiment, Review_count, Contains_Phone]
Index: []
Empty DataFrame
Columns: [Review, Sentiment, Review_count, Contains_Phone]
Index: []
Empty DataFrame
Columns: [Review, Sentiment, Review_count, Contains_Phone]
Index: []

In [ ]:
df["Characters"] = df["Review"].str.len()
print(df)

                Review Sentiment  Review_count  Contains_Phone  Characters
0    excellent product  Positive            17           False          17
1     very bad service  Negative            16           False          16
2      amazing quality  Positive            15           False          15
3  not worth the money  Negative            19           False          19

In [ ]:
df["words_column"] = df["Review"].apply( lambda x: len(x.split()))
print(df)

                Review Sentiment  Review_count  Contains_Phone  Characters  \
0    excellent product  Positive            17           False          17
1     very bad service  Negative            16           False          16
2      amazing quality  Positive            15           False          15
3  not worth the money  Negative            19           False          19

   words_column
0             2
1             3
2             2
3             4

In [ ]:
import pandas as pd

data = {
    "Feedback": [
        "Excellent teaching",
        "Need more practical sessions",
        "Very supportive faculty",
        "Assignments are difficult",
        "Great classroom environment",
        "Too much homework",
        "Helpful study materials",
        "Need better lab facilities",
        "Interesting lectures",
        "Poor internet connection"
    ],
    "Sentiment": [
        "Positive",
        "Negative",
        "Positive",
        "Negative",
        "Positive",
        "Negative",
        "Positive",
        "Negative",
        "Positive",
        "Negative"
    ]
}

df = pd.DataFrame(data)

print("First Five Records:")
print(df.head())

print("\nLast Five Records:")
print(df.tail())

First Five Records:
                       Feedback Sentiment
0            Excellent teaching  Positive
1  Need more practical sessions  Negative
2       Very supportive faculty  Positive
3     Assignments are difficult  Negative
4   Great classroom environment  Positive

Last Five Records:
                     Feedback Sentiment
5           Too much homework  Negative
6     Helpful study materials  Positive
7  Need better lab facilities  Negative
8        Interesting lectures  Positive
9    Poor internet connection  Negative

In [ ]:
df["Length"] = df["Feedback"].str.len()

longest_review = df.loc[df["Length"].idxmax()]

print(longest_review)

Feedback     Need more practical sessions
Sentiment                        Negative
Length                                 28
Name: 1, dtype: object